# Generated by Django 6.0.4 on 2026-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chat_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sent_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
