# Generated by Django 6.0.4 on 2026-05-03 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
