# Generated by Django 6.0.4 on 2026-05-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_feedback_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-submitted_at']},
        ),
    ]
