# Generated by Django 6.0.4 on 2026-04-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default-pfp.png', upload_to='foto_perfil/<django.db.models.query_utils.DeferredAttribute object at 0x7fa166362990>'),
        ),
    ]
