# Generated by Django 6.0.4 on 2026-04-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.FileField(blank=True, default='/media/default-pfp.png', upload_to='foto_perfil/<django.db.models.query_utils.DeferredAttribute object at 0x7fbbce3e6990>'),
        ),
    ]
