# Generated by Django 6.0.4 on 2026-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_pfp.png', null=True, upload_to='avatars/%Y/%M/'),
        ),
    ]
