# Generated by Django 6.0.4 on 2026-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='users.perfil'),
        ),
    ]
