# Generated by Django 6.0.4 on 2026-04-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_galeria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7fbf3075c050>/%Y/%m/%d'),
        ),
    ]
