# Generated by Django 6.0.4 on 2026-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_galeria_likes_alter_galeria_image_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f5f9aeaca50>/%Y/%m/%d'),
        ),
    ]
