# Generated by Django 6.0.4 on 2026-05-02 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_galeria_image_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f7445d04910>/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
