# Generated by Django 6.0.4 on 2026-05-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_galeria_likes_alter_galeria_image_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f33bbc4ce10>/%Y/%m/%d'),
        ),
    ]
