# Generated by Django 6.0.4 on 2026-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_galeria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f3d5cb554f0>/%Y/%m/%d'),
        ),
    ]
