# Generated by Django 6.0.4 on 2026-05-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_galeria_image_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f7be6b976b0>/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F13%2F74%2F20%2F137420f5b9c39bc911e472f5d20f053e.jpg%3Fnii%3Dt&f=1&nofb=1&ipt=3ca9275eb35ea303ae1a87b22894b43a152990422879f8b9278b00f66a2f4065', null=True, upload_to='avatars/%Y/%M/'),
        ),
    ]
