# Generated by Django 6.0.4 on 2026-05-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_galeria_image_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7fdabe77f4d0>/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_pfp.png', null=True, upload_to='avatars/%Y/%M/'),
        ),
    ]
