# Generated by Django 6.0.4 on 2026-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_galeria_image_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f7a0a39f7a0>/%Y/%m/%d'),
        ),
    ]
