# Generated by Django 6.0.4 on 2026-05-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_galeria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f29d179f7a0>/%Y/%m/%d'),
        ),
    ]
