# Generated by Django 6.0.4 on 2026-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_galeria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='posts/%Y/%m/%d'),
        ),
    ]
